# Generated by Django 5.2 on 2025-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emergencycontact_sossession_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsafearea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unsafearea',
            name='radius',
            field=models.FloatField(default=0.0),
        ),
    ]
